"""Application service for generating lagoon management reports.

Reports are generated as Markdown strings. The API layer handles
conversion to PDF/HTML on request.
"""
from __future__ import annotations

import logging
from datetime import UTC, datetime, timedelta
from typing import TYPE_CHECKING, Any, Protocol

if TYPE_CHECKING:
    from uuid import UUID

logger = logging.getLogger(__name__)


# ── Protocols ────────────────────────────────────────────────────────────────

class ReportDataProvider(Protocol):
    async def get_lagoon_summary(self, lagoon_id: UUID) -> dict[str, Any]: ...
    async def get_water_quality_stats(self, lagoon_id: UUID, days: int) -> dict[str, Any]: ...
    async def get_ecological_indicators(self, lagoon_id: UUID, days: int) -> dict[str, Any]: ...
    async def get_intervention_log(self, lagoon_id: UUID, days: int) -> list[dict[str, Any]]: ...
    async def get_recommendation_summary(self, lagoon_id: UUID, days: int) -> dict[str, Any]: ...
    async def get_compliance_status(self, lagoon_id: UUID, days: int) -> dict[str, Any]: ...
    async def get_infrastructure_status(self, lagoon_id: UUID) -> dict[str, Any]: ...
    async def get_loop_performance(self, lagoon_id: UUID, days: int) -> dict[str, Any]: ...


# ── Service ──────────────────────────────────────────────────────────────────

class ReportService:
    """Generates formatted reports from LOS operational and scientific data."""

    def __init__(self, data_provider: ReportDataProvider) -> None:
        self._data = data_provider

    async def generate_executive_report(
        self,
        lagoon_id: UUID,
        period_days: int = 30,
    ) -> str:
        """Generate a concise executive summary for management audiences.

        Covers: overall health score, key achievements, alerts, cost implications.
        """
        lagoon = await self._data.get_lagoon_summary(lagoon_id)
        wq = await self._data.get_water_quality_stats(lagoon_id, period_days)
        eco = await self._data.get_ecological_indicators(lagoon_id, period_days)
        compliance = await self._data.get_compliance_status(lagoon_id, period_days)
        recommendations = await self._data.get_recommendation_summary(lagoon_id, period_days)

        period_label = _period_label(period_days)
        generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        lagoon_name = lagoon.get("name", str(lagoon_id))

        health_score = _compute_health_score(wq, eco, compliance)
        health_rating = _health_rating(health_score)

        lines = [
            f"# Executive Report: {lagoon_name}",
            f"**Period:** {period_label}  |  **Generated:** {generated_at}",
            "",
            "---",
            "",
            "## Overall Health",
            "",
            f"**Health Score:** {health_score}/100 — {health_rating}",
            "",
            "| Dimension | Status |",
            "| --- | --- |",
            f"| Water Quality | {_status_badge(wq.get('overall_status', 'unknown'))} |",
            f"| Ecological | {_status_badge(eco.get('overall_status', 'unknown'))} |",
            f"| Compliance | {_status_badge(compliance.get('overall_status', 'unknown'))} |",
            "",
            "## Key Findings",
            "",
        ]

        key_findings = _extract_executive_findings(wq, eco, compliance)
        for finding in key_findings:
            lines.append(f"- {finding}")

        lines += [
            "",
            "## Alerts & Actions Required",
            "",
        ]
        alerts = compliance.get("active_violations", [])
        if alerts:
            for alert in alerts[:5]:
                lines.append(f"- **{alert.get('severity', 'INFO').upper()}**: {alert.get('description', '')}")
        else:
            lines.append("No active compliance violations.")

        lines += [
            "",
            "## Recommendations Summary",
            "",
            f"- **Pending review:** {recommendations.get('pending', 0)}",
            f"- **Approved this period:** {recommendations.get('approved', 0)}",
            f"- **Implemented:** {recommendations.get('implemented', 0)}",
            "",
            "---",
            f"*Report generated by Lagoons Operating System v1.0 for {lagoon_name}*",
        ]

        return "\n".join(lines)

    async def generate_scientific_report(
        self,
        lagoon_id: UUID,
        period_days: int = 30,
    ) -> str:
        """Generate a detailed scientific report for technical review.

        Includes: full water quality statistics, chemical and ecological
        analysis, model performance metrics, uncertainty estimates.
        """
        lagoon = await self._data.get_lagoon_summary(lagoon_id)
        wq = await self._data.get_water_quality_stats(lagoon_id, period_days)
        eco = await self._data.get_ecological_indicators(lagoon_id, period_days)
        infra = await self._data.get_infrastructure_status(lagoon_id)
        loop_perf = await self._data.get_loop_performance(lagoon_id, period_days)

        lagoon_name = lagoon.get("name", str(lagoon_id))
        generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        period_label = _period_label(period_days)

        lines = [
            f"# Scientific Technical Report: {lagoon_name}",
            f"**Period:** {period_label}  |  **Generated:** {generated_at}",
            "",
            "---",
            "",
            "## 1. Water Quality Parameters",
            "",
        ]

        wq_params = wq.get("parameters", {})
        if wq_params:
            lines += [
                "| Parameter | Mean | Std Dev | Min | Max | P10 | P90 | Status |",
                "| --- | ---: | ---: | ---: | ---: | ---: | ---: | --- |",
            ]
            for param, stats in wq_params.items():
                if isinstance(stats, dict):
                    lines.append(
                        f"| {param} | {stats.get('mean', 'N/A')} | "
                        f"{stats.get('std_dev', 'N/A')} | {stats.get('min', 'N/A')} | "
                        f"{stats.get('max', 'N/A')} | {stats.get('p10', 'N/A')} | "
                        f"{stats.get('p90', 'N/A')} | {stats.get('status', '–')} |"
                    )
        else:
            lines.append("No water quality data available for this period.")

        lines += [
            "",
            "## 2. Ecological Indicators",
            "",
            f"- **Bloom probability:** {eco.get('bloom_probability', 'N/A')}",
            f"- **Cyanobacteria advantage index:** {eco.get('cyanobacteria_advantage', 'N/A')}",
            f"- **Succession stage:** {eco.get('succession_stage', 'N/A')}",
            f"- **Trophic state:** {eco.get('trophic_state', 'N/A')}",
            "",
            "## 3. Infrastructure Status",
            "",
            f"- **Pump efficiency (mean):** {infra.get('pump_efficiency_mean', 'N/A')}",
            f"- **Inlet structures:** {infra.get('inlet_status', 'N/A')}",
            f"- **Outlet structures:** {infra.get('outlet_status', 'N/A')}",
            "",
            "## 4. Scientific Loop Performance",
            "",
            "| Loop | Last Run | Confidence | Status |",
            "| --- | --- | ---: | --- |",
        ]

        for loop_name, perf in loop_perf.items():
            if isinstance(perf, dict):
                lines.append(
                    f"| {loop_name} | {perf.get('last_run', 'Never')} | "
                    f"{perf.get('confidence', 'N/A')} | {perf.get('status', 'unknown')} |"
                )

        lines += [
            "",
            "---",
            f"*LOS Scientific Report — {lagoon_name}*",
        ]
        return "\n".join(lines)

    async def generate_compliance_report(
        self,
        lagoon_id: UUID,
        period_days: int = 30,
    ) -> str:
        """Generate a regulatory compliance report.

        Maps LOS parameter data against regulatory thresholds and
        produces a compliance statement suitable for submission.
        """
        lagoon = await self._data.get_lagoon_summary(lagoon_id)
        compliance = await self._data.get_compliance_status(lagoon_id, period_days)
        await self._data.get_water_quality_stats(lagoon_id, period_days)

        lagoon_name = lagoon.get("name", str(lagoon_id))
        generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        period_label = _period_label(period_days)

        standards = compliance.get("standards_applied", [])
        exceedances = compliance.get("exceedances", [])
        violations = compliance.get("active_violations", [])

        overall_status = compliance.get("overall_status", "unknown")

        lines = [
            f"# Compliance Report: {lagoon_name}",
            f"**Period:** {period_label}  |  **Generated:** {generated_at}",
            f"**Compliance Status:** {overall_status.upper()}",
            "",
            "---",
            "",
            "## Applicable Standards",
            "",
        ]

        if standards:
            for std in standards:
                lines.append(f"- {std}")
        else:
            lines.append("No regulatory standards configured.")

        lines += [
            "",
            "## Parameter Exceedances",
            "",
        ]

        if exceedances:
            lines += [
                "| Parameter | Date | Measured | Limit | % Exceedance |",
                "| --- | --- | ---: | ---: | ---: |",
            ]
            for exc in exceedances:
                lines.append(
                    f"| {exc.get('parameter')} | {exc.get('date')} | "
                    f"{exc.get('measured')} | {exc.get('limit')} | "
                    f"{exc.get('exceedance_pct', '–')} |"
                )
        else:
            lines.append("No parameter exceedances recorded during this period.")

        lines += [
            "",
            "## Active Violations",
            "",
        ]

        if violations:
            for v in violations:
                lines.append(
                    f"- **{v.get('severity', 'INFO').upper()}** — "
                    f"{v.get('description')} (since {v.get('since', 'unknown')})"
                )
        else:
            lines.append("No active compliance violations.")

        lines += [
            "",
            "## Compliance Statement",
            "",
            f"During the period {period_label}, {lagoon_name} was in "
            f"**{overall_status}** compliance with applicable environmental standards.",
            "",
            "---",
            "*This report is auto-generated by the Lagoons Operating System. "
            "Independent verification recommended before regulatory submission.*",
        ]

        return "\n".join(lines)

    async def generate_operational_report(
        self,
        lagoon_id: UUID,
        period_days: int = 7,
    ) -> str:
        """Generate a short operational report for operations staff.

        Covers: current conditions, interventions performed, upcoming tasks,
        sensor alerts, equipment status.
        """
        lagoon = await self._data.get_lagoon_summary(lagoon_id)
        wq = await self._data.get_water_quality_stats(lagoon_id, period_days)
        interventions = await self._data.get_intervention_log(lagoon_id, period_days)
        infra = await self._data.get_infrastructure_status(lagoon_id)
        recommendations = await self._data.get_recommendation_summary(lagoon_id, period_days)

        lagoon_name = lagoon.get("name", str(lagoon_id))
        generated_at = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")
        period_label = _period_label(period_days)

        lines = [
            f"# Operational Report: {lagoon_name}",
            f"**Period:** {period_label}  |  **Generated:** {generated_at}",
            "",
            "---",
            "",
            "## Current Conditions",
            "",
        ]

        latest = wq.get("latest_readings", {})
        if latest:
            lines += [
                "| Parameter | Value | Unit | Status |",
                "| --- | ---: | --- | --- |",
            ]
            for param, reading in latest.items():
                if isinstance(reading, dict):
                    lines.append(
                        f"| {param} | {reading.get('value', 'N/A')} | "
                        f"{reading.get('unit', '')} | {reading.get('status', '–')} |"
                    )
        else:
            lines.append("No recent sensor readings available.")

        lines += [
            "",
            "## Interventions This Period",
            "",
        ]

        if interventions:
            for iv in interventions:
                lines.append(
                    f"- **{iv.get('date', '')}** — {iv.get('type', '')} — "
                    f"{iv.get('description', '')} "
                    f"_(outcome: {iv.get('outcome', 'pending')})_"
                )
        else:
            lines.append("No interventions recorded.")

        lines += [
            "",
            "## Equipment Status",
            "",
            f"- **Primary pump:** {infra.get('primary_pump_status', 'N/A')}",
            f"- **Aerators:** {infra.get('aerator_status', 'N/A')}",
            f"- **SCADA connectivity:** {infra.get('scada_status', 'N/A')}",
            "",
            "## Actions Required",
            "",
            f"- Pending recommendations: {recommendations.get('pending', 0)}",
        ]

        pending = recommendations.get("pending_list", [])
        for rec in pending[:5]:
            lines.append(f"  - {rec.get('title', 'Unnamed recommendation')}")

        lines += [
            "",
            "---",
            f"*LOS Operational Report — {lagoon_name}*",
        ]
        return "\n".join(lines)


# ── Helpers ──────────────────────────────────────────────────────────────────

def _period_label(days: int) -> str:
    end = datetime.now(UTC)
    start = end - timedelta(days=days)
    return f"{start.strftime('%Y-%m-%d')} to {end.strftime('%Y-%m-%d')}"


def _compute_health_score(
    wq: dict[str, Any],
    eco: dict[str, Any],
    compliance: dict[str, Any],
) -> int:
    """Simple weighted average health score 0–100."""
    wq_score = _status_to_score(wq.get("overall_status", "unknown"))
    eco_score = _status_to_score(eco.get("overall_status", "unknown"))
    comp_score = _status_to_score(compliance.get("overall_status", "unknown"))
    weighted = wq_score * 0.40 + eco_score * 0.35 + comp_score * 0.25
    return round(weighted)


def _status_to_score(status: str) -> int:
    return {"good": 90, "acceptable": 70, "marginal": 50, "poor": 30, "unknown": 50}.get(
        status.lower(), 50
    )


def _health_rating(score: int) -> str:
    if score >= 80:
        return "Good"
    if score >= 60:
        return "Acceptable"
    if score >= 40:
        return "Marginal"
    return "Poor"


def _status_badge(status: str) -> str:
    symbols = {"good": "Good", "acceptable": "Acceptable", "marginal": "Marginal",
               "poor": "Poor", "unknown": "Unknown"}
    return symbols.get(status.lower(), status.capitalize())


def _extract_executive_findings(
    wq: dict[str, Any],
    eco: dict[str, Any],
    compliance: dict[str, Any],
) -> list[str]:
    findings = []
    if wq.get("do_concerns"):
        findings.append("Dissolved oxygen levels show periodic stress events.")
    if eco.get("bloom_risk", "low") != "low":
        findings.append(f"Algal bloom risk is elevated: {eco.get('bloom_risk')}.")
    if compliance.get("exceedance_count", 0) > 0:
        findings.append(
            f"{compliance['exceedance_count']} parameter exceedances recorded."
        )
    if not findings:
        findings.append("All key indicators within acceptable ranges.")
    return findings
